server:
#  port: 9090 #远程使用
  port: 8081 #本地测试
  servlet:
    session:
      timeout: 1800000 # 30分钟过期session
spring:
  application:
    name: work-admin
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://chenyilei.test:3306/worktraining?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
  # 关闭网页缓存
  thymeleaf:
    cache: false
  security:
    user:
      name: root
      password: root
  jackson:
    default-property-inclusion: non_null
#  session:
#    store-type: redis

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
#################  以下为个人自定义特别变量  ###################
cyl:
  security:
    enabled-security: false
    enabled-swagger: true     #启用swagger文档
    login-path: /authentication/login/*
    login-page: /index.html
    authentication-type: jwt    #登陆方式 normal 或 jwt形式,可扩展
    permit-all-when-no-filter: true  #没有拦截器的时候,不保护任何地址
    token-header: Authorization   # header中token验证的的key值
    jwt:
      keySecret: 'www.chenyilei.cn'
      ttl: 86400000
  ssl:                        #微信小程序必须要HTTPS协议,所以必要时可加上SSL
    enabled-ssl: false
    keyStore: 'C:\\Users\\Administrator\\Desktop\\School\\WorkingTraining\\work-web-admin\\src\\main\\resources\\resources\\chenyilei.jks'
    keyPassword: 1230
    keyStoreType: JKS
  system:
    upload-img-dir-perfix: C:/Users/Administrator/Desktop/School/WorkingTraining/images/
    visit-img-dir-perfix: https://chenyilei.mynatapp.cc/images/

#logging:
#  path: C:\\Users\\Administrator\\Desktop\\  #日志打印位置

#log4j:
#  logger:
#    com:
#      ibatis: debug
#      ibatis.common.jdbc.ScriptRunner: debug
#      ibatis.common.jdbc.SimpleDataSource: debug
#    java:
#      sql:
#        Connection: debug
#        PreparedStatement: debug
#        Statement: debug